repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: metrics-server
  url: https://kubernetes-sigs.github.io/metrics-server/
- name: grafana
  url: https://grafana.github.io/helm-charts
helmDefaults:
  tillerless: true
  verify: false
  wait: true
  timeout: 200

releases:
- name: metrics-server
  namespace: kube-system
  chart: metrics-server/metrics-server
  version: 3.8.0
  values:
  - args:
    - --kubelet-insecure-tls

- name: ingress
  namespace: kube-system
  chart: bitnami/nginx-ingress-controller
  version: 9.2.3
  values:
  - rbac:
      create: true
    controller:
      extraArgs:
    ## Depends on your cloud-provider. However, locally, it is must
        default-ssl-certificate: kube-system/ingress-tls-cert
 