{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "todo-api.fullname" . }}
  labels:
    {{- include "todo-api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "todo-api.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.cpuUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: {{ .Values.autoscaling.cpuTarget }}
          averageUtilization: {{ .Values.autoscaling.cpuUtilizationPercentage }}
  {{- end }}
  {{- if .Values.autoscaling.memoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: {{ .Values.autoscaling.memoryTarget }}
          averageUtilization: {{ .Values.autoscaling.memoryUtilizationPercentage }}
  {{- end }}
{{- end }}
